### PR TITLE
Discourage trait bounds on data structures

### LINKED ISSUE #6: Discourage trait bounds on data structures unless necessary
Example from flate2:

```rust
pub struct EncoderReader<R: Read> {
    inner: EncoderReaderBuf<BufReader<R>>,
}
```

Bounds like this are annoying because they transitively infect any structs containing this type. Usually trait bounds should go just on impl blocks, not on data structures.

There are two exceptions where trait bounds on data structures are required.

1. The data structure refers to an associated type of the trait. [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) is an example of this.
2. The data structure has a Drop impl that requires trait bounds. Rust currently requires all bounds on the Drop impl to also be present on the data structure.

Relevant flate2 issue: https://github.com/alexcrichton/flate2-rs/issues/88

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #6 

This is an attempt at a guideline for discouraging trait bounds on data structures. It looks like the discussion has run its course, but it might be a bit premature to capture this in a guideline. If so I guess we can move the discussion back to #6.

I thought I'd open this as a PR and get some general feedback on what we expect guidelines to look like, so I can align them better in the future. Some things I'm not sure about:

- Should all guidelines have an advantages and disadvantages section?
- Should all examples be self-contained or can they depend on previous ones?
- Should we keep discussion points succinct or expand on them a bit?
- How strict should our wording be about conforming to the guideline?

### CODE REVIEW

**Comment by dtolnay** [comment]
- Not all guidelines should have advantages and disadvantages sections. Where possible, I would prefer to phrase them as exceptions or conditions rather than disadvantages or hedges:
    - *disadvantage:* All motor vehicles should carry a spare tire. Disadvantages: spare tire adds a lot of weight to Formula One cars.
    - *hedge:* Most motor vehicles should usually carry a spare tire.
    - *exception:* All motor vehicles should carry a spare tire. Formula One cars are an exception because etc.
    - *condition:* All commuter vehicles should carry a spare tire.
- Examples can refer to other examples.
- I would cater to someone with a decent understanding of most of TRPL. Some obscure topics may need a link to the book or another reference.
- They are guidelines. Most of them will have exceptions and I trust people to think for themselves when applying guidelines to their use case. Let's focus on avoiding hedging and vague language.

**Comment by dtolnay** [comment]
In the Clippy thread we agreed on a broadly applicable blacklist that I would call out here. https://github.com/rust-lang-nursery/rust-clippy/issues/1689#issuecomment-299224950

Also I would like to mention the derive situation explicitly with an example because I see this all the time. It should explain why this is bad and why it is unnecessary.

```rust
#[derive(Clone, Debug, PartialEq)]
struct Bad<T: Clone + Debug + PartialEq> { /* ... */ }
```

**Comment by KodrAus** [comment]
Great, thanks for the clarification! :+1: Maybe we can add some more of this detail to the contributing file.

I'll update this to call out the blacklist covered by the lint and why the specific example of including derived traits in the bounds is problematic.

**Comment by KodrAus** [comment]
What do you reckon @dtolnay? Are you happy enough with this for me to merge?

**Comment by KodrAus** [comment]
Sounds like a good plan :+1:

**Comment by KodrAus** [comment]
So _this week_ ended up turning into _this month_ but I've reworded the guideline to focus on the compatibility aspect. I still don't think the voice is quite right, but I think a full pass over the content once we're happy with the coverage should solve that.

**Comment by dtolnay** [comment]
Nicely done, that is exactly what I had in mind. Go ahead and merge when ready. (I didn't notice anything off with the voice.)

**Pull request merged**
